### ISSUE TITLE
Couldn't find that add-on?

### ISSUE THREAD

**Issue by mikebaldry** [heroku/heroku-pg-extras#135]
I've installed heroku-pg-extras and when I run `heroku pg:bloat -a myapp` it returns `Couldn't find that add-on.` I have a heroku postgres database add-on, what have I done wrong?

**Comment by uhoh-itsmaciek** [comment]
@mikebaldry I *think* you are running into this issue: https://github.com/heroku/heroku-pg/issues/16 -- do you have a `DATABASE_URL` on this app? And if so, is it an actual attachment (you can check via `heroku addons`)? If you don't, you'll need to specify the addon-name (`postgresql-shiny-123`) or attachment name (as seen in `heroku addons` for the app--e.g., `DATABASE`) explicitly. We are working on improving this--sorry about the confusion. If you have more to add, can you please comment on the issue I linked above? I'm going to close this for now because I'm almost certain it's not an extras issue, but please reopen if you disagree.

**Comment by mikebaldry** [comment]
ah, it says to pass `DATABASE_URL`, instead I passed the actual name of the postgres addon, which was something like `HEROKU_POSTGRESQL_GOLD`, which was what it was listed as in `heroku addons -a appname`

Hope that helps someone!
