### ISSUE TITLE
Schema missing from certain commands

### ISSUE THREAD

**Issue by csuhta** [heroku/heroku-pg-extras#161]
The following commands do not print the schema name with the reported index or table names:

```
pg:seq-scans
pg:total-table-size
pg:table-size
pg:table-indexes-size
pg:records-rank
```

It's possible for two indexes or tables in different schemas to have the same name. The report output should include the schema name as a column to disambiguate.

**Comment by uhoh-itsmaciek** [comment]
Thanks for raising this. Unfortunately, I don't think we have the time to address this in the near future, but I'd be happy to review accept a patch if you'd like to contribute. Otherwise, we'll address this when we update the plugin for the current version of our CLI (it's relying on some legacy functionality now).

**Comment by jhubert** [comment]
@uhoh-itsmaciek I took a crack at this since it was blocking us as well. PR #180
