### ISSUE TITLE
column total_time does not exist when running outliers

### ISSUE THREAD

**Issue by espen** [heroku/heroku-pg-extras#188]
```
$ heroku pg:outliers

ERROR:  column "total_time" does not exist
LINE 2: SELECT interval '1 millisecond' * total_time AS total_exec_t...
                                          ^
 ▸    psql exited with code 1
```

**Comment by iriberri** [comment]
Thank you for reporting this issue and our apologies for the lack of updates here - this bug was addressed at https://github.com/heroku/heroku-pg-extras/pull/182.

Due to the command duplication between `pg:outliers` in this plugin and the core Heroku CLI, https://github.com/heroku/cli/pull/2051 is still pending to release for the main CLI. We hope to address this within the next couple days.

Thanks!
